using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TML.Generators;

public readonly struct CommandData
{
    /// <summary>
    ///     The type of the command.
    /// </summary>
    public readonly string Type;

    /// <summary>
    ///     The name of the command.
    /// </summary>
    public readonly string Name;

    /// <summary>
    ///     The method of the command.
    /// </summary>
    public readonly string Method;

    /// <summary>
    ///     Initializes a new instance of the <see cref="CommandData" /> struct.
    /// </summary>
    /// <param name="type">
    ///     The type of the command.
    /// </param>
    /// <param name="name">
    ///     The name of the command.
    /// </param>
    /// <param name="method">
    ///     The method of the command.
    /// </param>
    private CommandData(string type, string name, string method)
    {
        Type = type;
        Name = name;
        Method = method;
    }

    /// <summary>
    ///     Creates a <see cref="CommandData" /> instance from the specified generator attribute context.
    /// </summary>
    /// <param name="context">
    ///     The generator attribute context that contains the command data.
    /// </param>
    /// <returns>
    ///     A <see cref="CommandData" /> instance from the specified generator attribute context.
    /// </returns>
    public static CommandData From(GeneratorAttributeSyntaxContext context)
    {
        var method = (IMethodSymbol)context.TargetSymbol;
        var attribute = context.Attributes[0];

        return new CommandData(method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), (string)attribute.ConstructorArguments[0].Value, method.Name);
    }
}

[Generator(LanguageNames.CSharp)]
public sealed class CommandGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     The qualified name of the type of the command attribute.
    /// </summary>
    private const string ATTRIBUTE_TYPE_NAME = "TML.Commands.CommandAttribute";

    /// <summary>
    ///     The name of the file generated by the generator.
    /// </summary>
    private const string GENERATED_FILE_NAME = "CommandDispatcher.g.cs";

    /// <inheritdoc />
    void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commands = context.SyntaxProvider.ForAttributeWithMetadataName
        (
            ATTRIBUTE_TYPE_NAME,
            static (node, _) => node is MethodDeclarationSyntax,
            static (context, _) => CommandData.From(context)
        );

        context.RegisterSourceOutput(commands.Collect(), Generate);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<CommandData> commands)
    {
        var source = new StringBuilder();

        source.AppendLine("// <auto-generated/>");
        source.AppendLine();
        source.AppendLine("namespace TML.Commands;");
        source.AppendLine();
        source.AppendLine("internal static partial class CommandDispatcher");
        source.AppendLine("{");
        source.AppendLine("    /// <inheritdoc />");
        source.AppendLine("    internal static partial void Execute(string[] args)");
        source.AppendLine("    {");
        source.AppendLine("        if (args.Length == 0)");
        source.AppendLine("        {");
        source.AppendLine("            return;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        var command = args[0].ToLowerInvariant();");
        source.AppendLine();
        source.AppendLine("        switch (command)");
        source.AppendLine("        {");

        foreach (var command in commands)
        {
            source.AppendLine($"            case \"{command.Name}\":");
            source.AppendLine($"                {command.Type}.{command.Method}(args[1..]);");
            source.AppendLine("                break;");
        }

        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource(GENERATED_FILE_NAME, SourceText.From(source.ToString(), Encoding.UTF8));
    }
}